package com.ftn.sbnz.kjar.rules

import com.ftn.sbnz.model.ghosts.Ghost;
import com.ftn.sbnz.model.ghosts.GhostCandidate;
import com.ftn.sbnz.model.evidence.Evidence;
import com.ftn.sbnz.model.evidence.CurrentEvidence;
import com.ftn.sbnz.model.traits.DerivedTrait;
import com.ftn.sbnz.model.observations.HuntObservation;
import com.ftn.sbnz.model.evidence.EvidenceMatch;
import com.ftn.sbnz.model.ghosts.GhostEliminated;


rule "Score_Confirmed_Evidence"
    salience 20
when
    $input : CurrentEvidence()
    $e     : Evidence() from $input.getConfirmedEvidence()
    $g     : Ghost($evidences : evidences, $name : name)
    eval($evidences.contains($e))
    not GhostEliminated(ghostName == $name)
    not EvidenceMatch(ghostName == $name, evidence == $e)   // idempotent
then
    insert(new EvidenceMatch($name, $e));
    System.out.println("[EVIDENCE MATCH] " + $name + " matches " + $e);
end

rule "Score_Ghost_Traits_Dynamically"
    salience 12
when
    DerivedTrait($trait : traitName)
    $g : Ghost(traits contains $trait, $name : name)
    not GhostEliminated(ghostName == $name)
    not TraitMatch(ghostName == $name, traitName == $trait)
then
    insert(new TraitMatch($name, $trait));
    System.out.println("[TRAIT MATCH] " + $name + " matches trait " + $trait);
end
